posts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'articles/$', views.post_list, name='post_list'),
    url(r'articles/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>[a-zA-Z0-9\-]+)/$', views.post_detail, name='post_detail'),
]

thoughtplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('posts.urls')),

    url(r'^$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^keybase\.txt$', TemplateView.as_view(
        template_name='keybase.txt',
        content_type='text/plain',
    ), name='keybase'),
    url(r'^projects/$', TemplateView.as_view(template_name='projects.html'), name='projects'),
]

comments/models.py
from django.db import models

from thoughtplace.cache import delete_cached_fragment


class Comment(models.Model):
    url = models.CharField(db_index=True, max_length=255)
    ip = models.CharField(max_length=255)

    name = models.CharField(help_text='Name. Leave blank for anonymous comments.', max_length=255, blank=True, null=True)
    website = models.URLField(help_text='Website. Optional.', max_length=255, blank=True, null=True)

    comment = models.TextField(
        help_text='''
Comment here.  To reply to someone, refer to them by name or to their comment by number e.g. "Jane #4", "comment #11", etc.
'''[1:-1],
    )

    moderator = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return '#{0} on {1} by {2}'.format(
            self.id,
            self.url,
            self.name,
        )

    def save(self, *args, **kwargs):
        self.delete_related_cache()

        super(Comment, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.delete_related_cache()

        super(Comment, self).delete(*args, **kwargs)

    def delete_related_cache(self):
        # Delete cached sections for related post or thought
        delete_cached_fragment('obj', self.url, 'comments')

    @property
    def display_name(self):
        return 'David Sanders' if self.moderator else (self.name or 'Anonymous')

    @property
    def display_website(self):
        return None if self.moderator else self.website

posts/models.py
import os
import re

from dateutil.parser import parse
from django.conf import settings
from django.core.urlresolvers import reverse
from yaml import load
try:
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader

from thoughtplace.utils import convert_with_tex


class Post(object):
    DATE_RE = re.compile(r'^.*/(\d{4})/(\d{1,2})/(\d{1,2})/([a-zA-Z0-9\-]+)\.md$')
    OBJECTS_DIR = os.path.join(settings.BASE_DIR, 'posts', 'objects')
    DETAIL_URL = 'post_detail'

    def __init__(self, path):
        with open(path, 'r') as f:
            content = f.read()

        # Get url and identifying data from file path
        self.id = self.DATE_RE.match(path).groups()
        self.url = reverse(self.DETAIL_URL, args=self.id)

        # Parse raw post content
        parts = content.split('---\n')
        parts = list(filter(bool, parts))

        # Load data from frontmatter yaml
        frontmatter = load(parts[0], Loader=Loader)

        self.title = convert_with_tex(frontmatter['title'])

        published = frontmatter.get('published')
        self.published = parse(published) if published else None

        # Convert post body from markdown to html
        self.body = convert_with_tex(parts[1].strip())

    @classmethod
    def get_objects(cls):
        if hasattr(cls, '_objects') and not settings.DEBUG:
            return cls._objects

        object_files = []
        for root, dirs, files in os.walk(cls.OBJECTS_DIR):
            for f in files:
                if f.endswith('.md'):
                    object_files.append(os.path.join(root, f))

        cls._objects = {o.id: o for o in map(cls, object_files)}

        return cls._objects

    @classmethod
    def get_object(cls, id):
        return cls.get_objects()[id]

comments/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.mail import send_mail

from .models import Comment


class CommentForm(forms.ModelForm):
    not_a_you_know_what = forms.CharField(required=False, widget=forms.HiddenInput(), initial='pwned!')

    class Meta:
        model = Comment
        fields = (
            'name',
            'website',
            'comment',
            'not_a_you_know_what',
        )

    def __init__(self, *args, **kwargs):
        self._object = kwargs.pop('obj', None)
        self._request = kwargs.pop('request', None)

        super(CommentForm, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        cd = super(CommentForm, self).clean(*args, **kwargs)

        if cd['not_a_you_know_what']:
            raise ValidationError('Nope!')

    def save(self, *args, **kwargs):
        kwargs['commit'] = False
        comment = super(CommentForm, self).save(*args, **kwargs)

        comment.url = self._object.url
        comment.ip = self._request.META['REMOTE_ADDR']

        comment.save()

        # Send notification email
        admin_emails = list(User.objects.filter(is_superuser=True).values_list('email', flat=True))
        send_mail(
            f'{comment.display_name} commented on {comment.url}',
            comment.comment,
            settings.DEFAULT_FROM_EMAIL,
            admin_emails,
            fail_silently=False,
        )

        return comment

posts/views.py
from django.contrib import messages
from django.http import Http404
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView

from comments.forms import CommentForm
from comments.models import Comment
from thoughtplace.cache import ONE_YEAR_TIMEOUT
from .models import Post


class PostListView(TemplateView):
    template_name = 'posts/post_list.html'
    pseudo_model = Post

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)

        objects = self.pseudo_model.get_objects().values()
        objects = filter(lambda i: i.published, objects)
        objects = sorted(objects, key=lambda i: i.published, reverse=True)

        context['objects'] = objects

        return context

post_list = PostListView.as_view()


class PostDetailView(TemplateView):
    template_name = 'posts/post_detail.html'
    pseudo_model = Post

    def post(self, *args, **kwargs):
        return super(PostDetailView, self).get(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)

        post_id = (
            self.kwargs['year'],
            self.kwargs['month'],
            self.kwargs['day'],
            self.kwargs['slug'],
        )

        try:
            obj = self.pseudo_model.get_object(post_id)
        except KeyError:
            raise Http404

        context['obj'] = obj
        context['comments'] = Comment.objects.filter(url=obj.url)

        if self.request.method == 'POST':
            form = CommentForm(self.request.POST, obj=obj, request=self.request)

            if form.is_valid():
                form.save()
                messages.success(self.request, 'Your comment has been posted.')
        else:
            form = CommentForm()

        context['form'] = form
        context['ONE_YEAR_TIMEOUT'] = ONE_YEAR_TIMEOUT

        return context

post_detail = never_cache(PostDetailView.as_view())

templates/about.html
{% extends 'base.html' %}

{% block container-class %}uk-container-xsmall{% endblock %}

{% block article-content %}
<div class="uk-text-center uk-margin-small-top">
  <p class="uk-margin-remove-bottom">
  Thoughts about technology and other things by this guy:
  </p>

  <img class="uk-align-center uk-border-rounded" width="230" height="230" src="https://s.gravatar.com/avatar/c991993ee238fbae918f93f46edac3cd?s=460"/>

  <p class="uk-margin-medium-top">
  <a href="mailto:davesque@gmail.com">Contact</a> /
  <a href="https://cdn.rawgit.com/davesque/resume/089dd43/Resume%20-%20Charles%20David%20Sanders.pdf">R&eacute;sum&eacute;</a>
  </p>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html>
<head>
  <title>thought.place</title>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="description" content="thought.place | a blog by David Sanders">
  <meta name="keywords" content="Web Development, Software Engineering, Computer Science, Python, Haskell, Boulder, Denver, Colorado">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.rawgit.com/davesque/computer-modern-web-font/master/fonts.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">

  <!-- UIkit CSS -->
  {% compress css %}
  <link rel="stylesheet" type="text/x-scss" href="{% static 'site.scss' %}" />
  {% endcompress %}

  <!-- jQuery required for UIkit -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <!-- UIkit JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.25/js/uikit.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.25/js/uikit-icons.min.js"></script>

  <!-- KaTeX -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.css" integrity="sha384-exe4Ak6B0EoJI0ogGxjJ8rn+RN3ftPnEQrGwX59KTCl5ybGzvHGKjhPKk/KC3abb" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.js" integrity="sha384-OMvkZ24ANLwviZR2lVq8ujbE/bUO8IR1FdBrKLQBI14Gq5Xp/lksIccGkmKL8m+h" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/contrib/auto-render.min.js" integrity="sha384-cXpztMJlr2xFXyDSIfRWYSMVCXZ9HeGXvzyKTYrn03rsMAlOtIQVzjty5ULbaP8L" crossorigin="anonymous"></script>

  {% comment %}
  <!-- MathJax -->
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      CommonHTML: {
        mtextFontInherit: true
      }
    });

    MathJax.Hub.Register.StartupHook("TeX Jax Ready", function () {
      var MML = MathJax.ElementJax.mml,
          TEX = MathJax.InputJax.TeX;

      TEX.Definitions.macros.sfrac = "myBevelFraction";

      TEX.Parse.Augment({
        myBevelFraction: function (name) {
          var num = this.ParseArg(name),
              den = this.ParseArg(name);
          this.Push(MML.mfrac(num,den).With({bevelled: true}));
        }
      });
    });
  </script>
  <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>
  {% endcomment %}
</head>

{% url 'about' as about_url %}
{% url 'post_list' as post_list_url %}
{% url 'projects' as projects_url %}

<body>
  <div class="uk-offcanvas-content">
    <div class="uk-background-primary">
      <nav class="uk-navbar-container" uk-navbar>
        <div class="uk-navbar-left">
          <a href="/" class="uk-navbar-item uk-logo">thought.place</a>
        </div>

        <div class="uk-navbar-right">
          <ul class="uk-navbar-nav">
            <li class="uk-visible@s {% if request.path == '/' %}uk-active{% endif %}"><a href="{{ about_url }}">about</a></li>
            <li class="uk-visible@s {% if post_list_url in request.path %}uk-active{% endif %}"><a href="{{ post_list_url }}">articles</a></li>
            <li class="uk-visible@s {% if projects_url in request.path %}uk-active{% endif %}"><a href="{{ projects_url }}">projects</a></li>

            <a href="#offcanvas-nav-primary" class="uk-navbar-toggle uk-hidden@s" type="button" uk-navbar-toggle-icon uk-toggle></a>
          </ul>
        </div>
      </nav>
    </div>

    <div class="uk-container {% block container-class %}uk-container-small{% endblock %}">
      {% block content %}
      <article class="uk-article {% block article-class %}uk-text-justify{% endblock %}">
        {% block article-content %}{% endblock %}
      </article>
      {% endblock %}

      <footer class="uk-text-center uk-margin-large-bottom">&copy; 2011-2018 David Sanders</footer>
    </div>

    <div id="offcanvas-nav-primary" uk-offcanvas="overlay: true">
      <div class="uk-offcanvas-bar uk-box-shadow-large uk-flex uk-flex-column">
        <ul class="uk-nav uk-nav-primary uk-nav-center uk-margin-auto-vertical">
          <li class="{% if request.path == '/' %}uk-active{% endif %}"><a href="{{ about_url }}">About</a></li>
          <li class="{% if post_list_url in request.path %}uk-active{% endif %}"><a href="{{ post_list_url }}">Articles</a></li>
          <li class="{% if projects_url in request.path %}uk-active{% endif %}"><a href="{{ projects_url }}">Projects</a></li>
        </ul>
      </div>
    </div>
  </div>

  <script>
  renderMathInElement(document.body);
  </script>
</body>

templates/posts/index.html
{% extends 'base.html' %}

{% block article-content %}
{% for obj in objects %}
<section class="{% if not forloop.last %}uk-margin-medium-bottom{% endif %}">
  <hgroup>
    <h2 class="uk-margin-small-bottom"><a class="uk-link-text" href="{{ obj.url }}">{{ obj.title }}</a></h2>
    <h3 class="uk-margin-small-top">{{ obj.published|date:'Y.n.j' }}</h3>
  </hgroup>

  <p>{{ obj.body|truncatewords_html:30|striptags }}</p>
</section>
{% endfor %}
{% endblock %}

templates/posts/post.html
{% extends 'base.html' %}
{% load cache %}

{% block content %}
{% cache ONE_YEAR_TIMEOUT obj view.request.path %}
<article class="uk-article uk-text-justify">
  <h1 class="uk-heading-primary">{{ obj.title }}</h1>

  <section>
    {{ obj.body|safe }}
  </section>
</article>
{% endcache %}

{#<section>#}
{#  <section>#}
{#    <h2>Leave a comment:<h2>#}

{#    <div id="token" style="display: none;">{{ csrf_token }}</div>#}

{#    <form method="post">#}
{#      <input type="hidden" id="id_csrfmiddlewaretoken" name="csrfmiddlewaretoken">#}

{#      <table>#}
{#        {{ form.as_table }}#}
{#      </table>#}

{#      <div><input type="submit" value="Submit"></div>#}
{#    </form>#}

{#    <script>#}
{#      $('#id_csrfmiddlewaretoken').val($('#token').text());#}
{#      $('#id_not_a_you_know_what').val('');#}
{#    </script>#}

{#    <noscript>#}
{#      If you have javascript disabled, you probably know a thing or two about#}
{#      web pages.  In order to submit this comment form, please copy the text#}
{#      from the element with id "token" into the form field with id#}
{#      "id_csrfmiddlewaretoken".  Also, delete the value in the form field with#}
{#      id "id_not_a_you_know_what" (this is a honeypot field).#}
{#    </noscript>#}
{#  </section>#}

{#{% cache ONE_YEAR_TIMEOUT obj view.request.path 'comments' %}#}
{#  {% for c in comments %}#}
{#  <section>#}
{#    <h2 class="{% if c.moderator %}moderator{% endif %}">#}
{#      {% if c.display_website %}#}
{#      <a href="{{ c.display_website }}">{{ c.display_name }}</a> says:#}
{#      {% else %}#}
{#      {{ c.display_name }} says:#}
{#      {% endif %}#}
{#    <h2>#}

{#    <p><em>Comment #{{ forloop.counter }} posted on {{ c.created_at|date:'Y.n.j \a\t f a e' }}</em></p>#}

{#    {% if c.deleted %}#}
{#    [deleted]#}
{#    {% else %}#}
{#    {{ c.html_content|safe }}#}
{#    {% endif %}#}
{#  </section>#}
{#  {% endfor %}#}
{#{% endcache %}#}
{#</section>#}
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load cache thoughtplace_tags %}

{% block content %}
{% cache ONE_YEAR_TIMEOUT obj view.request.path %}
<article class="uk-article uk-text-justify uk-margin-remove-bottom">
  <h1 class="uk-heading-primary uk-margin-small-bottom">{{ obj.title|safe }}</h1>
  <div class="uk-text-center uk-margin-sm-med-bottom">
    David Sanders{% if obj.published %} &mdash; {{ obj.published|date:'Y/n/j' }}{% endif %}
  </div>

  <section>
    {{ obj.body|safe }}
  </section>
</article>
{% endcache %}

<section class="uk-margin-top">
  <h2>Leave a comment:</h2>

  <div id="token" style="display: none;">{{ csrf_token }}</div>

  <form method="post">
    <fieldset class="uk-fieldset">
      {% csrf_token %}
      {{ form.not_a_you_know_what }}

      {{ form.non_field_errors }}

      <p class="uk-margin-remove-top">
      {{ form.name|add_placeholder|add_classes:"uk-input" }}
      {{ form.name.errors }}
      </p>

      <p>
      {{ form.website|add_placeholder|add_classes:"uk-input" }}
      {{ form.website.errors }}
      </p>

      <p>
      {{ form.comment|add_placeholder|add_classes:"uk-textarea" }}
      {{ form.comment.errors }}
      </p>

      <input type="submit" value="submit" class="uk-button uk-button-default uk-align-right uk-text-lowercase">
    </fieldset>
  </form>

  <script>
    $('#id_csrfmiddlewaretoken').val($('#token').text());
    $('#id_not_a_you_know_what').val('');
  </script>

  <noscript>
    If you have javascript disabled, you probably know a thing or two about
    web pages.  In order to submit this comment form, please copy the text
    from the element with id "token" into the form field with id
    "id_csrfmiddlewaretoken".  Also, delete the value in the form field with
    id "id_not_a_you_know_what" (this is a honeypot field).
  </noscript>
</section>

{% cache ONE_YEAR_TIMEOUT obj view.request.path 'comments' %}
{% for c in comments %}
  <section class="uk-margin-medium-bottom">
    <h2 class="uk-h4 uk-margin-remove-bottom {% if c.moderator %}moderator{% endif %}">
      {% if c.display_website %}
      <a href="{{ c.display_website }}">{{ c.display_name }}</a> says:
      {% else %}
      {{ c.display_name }} says:
      {% endif %}
    </h2>

    <p class="uk-text-small uk-margin-small-top">
    <em>Comment #{{ forloop.counter }} ({{ c.created_at|date:'Y/n/j f a e' }})</em>
    </p>

    {% if c.deleted %}[deleted]{% else %}{{ c.comment }}{% endif %}
  </section>
{% endfor %}
{% endcache %}
{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load thoughtplace_tags %}

{% block article-content %}
{% for obj in objects %}
<section class="{% if not forloop.last %}uk-margin-medium-bottom{% endif %}">
  <hgroup>
    <h2 class="uk-margin-small-bottom"><a class="uk-link-text" href="{{ obj.url }}">{{ obj.title|safe }}</a></h2>
    <div class="uk-margin-small-top">{{ obj.published|date:'Y/n/j' }}</div>
  </hgroup>

  <p>{{ obj.body|remove_tags:"h1 h2 h3 h4"|truncatewords_html:30|striptags }}</p>
</section>
{% endfor %}
{% endblock %}

templates/projects.html
{% extends 'base.html' %}

{% block article-content %}
<section>
  <div uk-grid>
    <div class="uk-width-expand" uk-leader><a class="uk-text-large uk-link-text" href="https://github.com/davesque/django-rest-framework-simplejwt">simple jwt</a></div>
    <div class="uk-text-large">python</div>
  </div>

  <p>A JSON Web Token auth plugin for the Django REST Framework.</p>
</section>

<section>
  <div uk-grid>
    <div class="uk-width-expand" uk-leader><a class="uk-text-large uk-link-text" href="https://github.com/davesque/s">s</a></div>
    <div class="uk-text-large">shell</div>
  </div>

  <p>A simple shell script manager.</p>
</section>

<section>
  <div uk-grid>
    <div class="uk-width-expand" uk-leader><a class="uk-text-large uk-link-text" href="https://github.com/davesque/go.py">go.py</a></div>
    <div class="uk-text-large">python</div>
  </div>

  <p>A text-based go game written in python.</p>
</section>

<section>
  <div uk-grid>
    <div class="uk-width-expand" uk-leader><a class="uk-text-large uk-link-text" href="https://github.com/davesque/gitfuse">gitfuse</a></div>
    <div class="uk-text-large">python</div>
  </div>

  <p>Easily mount git repositories as read-only file systems using FUSE.</p>
</section>

<section>
  <div uk-grid>
    <div class="uk-width-expand" uk-leader><a class="uk-text-large uk-link-text" href="https://github.com/davesque/thought.place">thought.place</a></div>
    <div class="uk-text-large">python</div>
  </div>

  <p>This website.</p>
</section>

<section>
  <a class="uk-text-large uk-link-text" href="https://github.com/davesque">etc, etc&hellip;</a>
</section>
{% endblock %}